package me.risky.talk.comment.domain;

import java.util.Date;

public class TComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.Id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.key
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_time
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.ownerAccout
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private String owneraccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.type
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.reply_id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    private String replyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.Id
     *
     * @return the value of t_comment.Id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.Id
     *
     * @param id the value for t_comment.Id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.key
     *
     * @return the value of t_comment.key
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.key
     *
     * @param key the value for t_comment.key
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_time
     *
     * @return the value of t_comment.create_time
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_time
     *
     * @param createTime the value for t_comment.create_time
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.ownerAccout
     *
     * @return the value of t_comment.ownerAccout
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public String getOwneraccout() {
        return owneraccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.ownerAccout
     *
     * @param owneraccout the value for t_comment.ownerAccout
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setOwneraccout(String owneraccout) {
        this.owneraccout = owneraccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.type
     *
     * @return the value of t_comment.type
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.type
     *
     * @param type the value for t_comment.type
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reply_id
     *
     * @return the value of t_comment.reply_id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reply_id
     *
     * @param replyId the value for t_comment.reply_id
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId;
    }
}