package me.risky.talk.comment.domain;

import java.util.Date;

public class TComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.Id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.url_key
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private String urlKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_time
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.owner_accout
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private String ownerAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.type
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.reply_id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    private String replyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.Id
     *
     * @return the value of t_comment.Id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.Id
     *
     * @param id the value for t_comment.Id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.url_key
     *
     * @return the value of t_comment.url_key
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public String getUrlKey() {
        return urlKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.url_key
     *
     * @param urlKey the value for t_comment.url_key
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setUrlKey(String urlKey) {
        this.urlKey = urlKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_time
     *
     * @return the value of t_comment.create_time
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_time
     *
     * @param createTime the value for t_comment.create_time
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.owner_accout
     *
     * @return the value of t_comment.owner_accout
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public String getOwnerAccout() {
        return ownerAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.owner_accout
     *
     * @param ownerAccout the value for t_comment.owner_accout
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setOwnerAccout(String ownerAccout) {
        this.ownerAccout = ownerAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.type
     *
     * @return the value of t_comment.type
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.type
     *
     * @param type the value for t_comment.type
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reply_id
     *
     * @return the value of t_comment.reply_id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reply_id
     *
     * @param replyId the value for t_comment.reply_id
     *
     * @mbggenerated Fri Sep 05 15:50:28 CST 2014
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId;
    }
}