package me.risky.talk.server.domain;

import java.util.Date;

public class TFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.id
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.name
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.create_time
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.thumb_url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private String thumbUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.type
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.status
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.size
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.id
     *
     * @return the value of t_file.id
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.id
     *
     * @param id the value for t_file.id
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.name
     *
     * @return the value of t_file.name
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.name
     *
     * @param name the value for t_file.name
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.url
     *
     * @return the value of t_file.url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.url
     *
     * @param url the value for t_file.url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.create_time
     *
     * @return the value of t_file.create_time
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.create_time
     *
     * @param createTime the value for t_file.create_time
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.thumb_url
     *
     * @return the value of t_file.thumb_url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public String getThumbUrl() {
        return thumbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.thumb_url
     *
     * @param thumbUrl the value for t_file.thumb_url
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.type
     *
     * @return the value of t_file.type
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.type
     *
     * @param type the value for t_file.type
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.status
     *
     * @return the value of t_file.status
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.status
     *
     * @param status the value for t_file.status
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.size
     *
     * @return the value of t_file.size
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.size
     *
     * @param size the value for t_file.size
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    public void setSize(Integer size) {
        this.size = size;
    }
}