package me.risky.talk.comment.persistence;

import java.util.List;
import me.risky.talk.comment.domain.TComment;
import me.risky.talk.comment.domain.TCommentExample;
import org.apache.ibatis.annotations.Param;

public interface TCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int countByExample(TCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int deleteByExample(TCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int insertSelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    List<TComment> selectByExample(TCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    TComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") TComment record, @Param("example") TCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int updateByExample(@Param("record") TComment record, @Param("example") TCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int updateByPrimaryKeySelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat May 03 16:28:04 CST 2014
     */
    int updateByPrimaryKey(TComment record);
}