package me.risky.talk.server.persistence;

import java.util.List;
import me.risky.talk.server.domain.TContent;
import me.risky.talk.server.domain.TContentExample;
import org.apache.ibatis.annotations.Param;

public interface TContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int countByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int deleteByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int insert(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int insertSelective(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    List<TContent> selectByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    TContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") TContent record, @Param("example") TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByExample(@Param("record") TContent record, @Param("example") TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByPrimaryKeySelective(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByPrimaryKey(TContent record);
}