package me.risky.talk.server.persistence;

import me.risky.talk.server.domain.TFile;
import me.risky.talk.server.domain.TFileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    TFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Dec 24 10:31:34 CST 2014
     */
    int updateByPrimaryKey(TFile record);
}