package me.risky.talk.server.persistence;

import java.util.List;
import me.risky.talk.server.domain.TFile;
import me.risky.talk.server.domain.TFileExample;
import org.apache.ibatis.annotations.Param;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    TFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Thu Dec 25 11:21:32 CST 2014
     */
    int updateByPrimaryKey(TFile record);
}